name=ESP32Synth
version=2.3.5
author=Danilo Gabriel
maintainer=Danilo Gabriel
sentence=High-quality synthesizer library, lightweight, versatile, and polyphonic (+80 channels) for the ESP32.
paragraph=Supports I2S, PDM, and internal DAC. Good and efficient: ESP32Synth.
category=Signal Input/Output
url=https://github.com/danilogcrf2-oss/ESP32Synth
architectures=esp32,esp32s3
includes=ESP32Synth.h


